github_url = "https://github.com/fvarno/fedsim/"

[version]
current = "0.6.0"
regex = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "setup.py"
search = 'version="{current_version}"'

[[file]]
src = "docs/source/conf.py"
search = 'version = release = "{current_version}"'

[[file]]
src = "fedsim/__init__.py"
search = '__version__ = "{current_version}"'

[[file]]
src = "fedsim_cli/__init__.py"
search = '__version__ = "{current_version}"'


[[before_commit]]
name = "check changelog"
cmd = "grep -q {new_version} CHANGELOG.rst"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
